---
name: coverage
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Ruby (3.2)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
    - uses: amancevice/setup-code-climate@v0
      with:
        cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
    - run: cc-test-reporter before-build
    - name: Build and test with RSpec
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rspec
    - run: cc-test-reporter after-build
